# Generated by Django 3.1.4 on 2020-12-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201225_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='da_duyet',
            field=models.BooleanField(default=False),
        ),
    ]
