# Generated by Django 3.1.4 on 2020-12-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201221_0813'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stcck',
            new_name='Stock',
        ),
    ]
