# Generated by Django 3.1.4 on 2020-12-21 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201221_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shoe',
        ),
        migrations.AddField(
            model_name='stock',
            name='shoe',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.shoe'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='size',
        ),
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
