# Generated by Django 3.1.4 on 2020-12-21 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201221_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='shoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.shoe'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.size'),
        ),
    ]
