# Generated by Django 3.1.4 on 2020-12-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201221_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('size', 'shoe')},
        ),
    ]
