# Generated by Django 3.1.4 on 2020-12-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201221_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promation',
            old_name='da_su_dung',
            new_name='is_used',
        ),
        migrations.RenameField(
            model_name='promation',
            old_name='giam_gia',
            new_name='promote',
        ),
        migrations.AddField(
            model_name='promation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
