# Generated by Django 3.1.4 on 2020-12-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201221_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promation',
            new_name='Promotion',
        ),
    ]
