# Generated by Django 3.1.4 on 2020-12-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_shoe_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
